### ISSUE TITLE
Datatypes in plugin 

### ISSUE THREAD

**Issue by juancanobenito** [oeg-upm/helio#10]
Data types in plugins dont work properly.

Mapping example:

```
"properties"  : [
...
    "predicate" : "http://www.oeg.es/ontology#block_number", 
    "object" : "{$.Number}",
    "datatype" : "http://www.w3.org/2001/XMLSchema#positiveInteger",
    "is_literal" : true
   },{
    "predicate" : "http://www.oeg.es/ontology#timestamp", 
    "object" : "{$.Timestamp}",
    "datatype" : "http://www.w3.org/2001/XMLSchema#timestamp",
    "is_literal" : true
  },
...
```

Output:

```
<http://www.oeg.es/ontology#block_number> "756"^^<http://www.w3.org/2001/XMLSchema#string> ;
<http://www.oeg.es/ontology#timestamp> "1479658624"^^<http://www.w3.org/2001/XMLSchema#string> .
```

**Comment by juancanobenito** [comment]
As far as I know, this bug is produced in Windows 10. To replicate this error, the following steps should be followed:

1. Use the materialiser (version 0.3.8) with Windows or Linux for Windows.
2. Add/change in the mapping some datatype
3. Use the materialiser again with Windows or Linux for Windows.
4. The new datatypes are not showed.

To fix it, the databases in helio-storage must be delete. Then, the first time you tried to generate the mappings the program will be locked in "Writting data ..". The second time works correctly, but if you change the mapping, repeat from step 1.

**Comment by AndreaCimminoArriaga** [comment]
Could you try to write `"is_literal" : "True"` instead of `"is_literal" : true` ? I think this is the whole thing

**Comment by AndreaCimminoArriaga** [comment]
Thanks for reporting, we have changed the way in which datatypes are generated. Now dynamic datatypes are supported. I will close the comment, please verify if this error persists and let us know if that is the case. Many thanks
