### ISSUE TITLE
Problem if Helio is deployed in port 8081

### ISSUE THREAD

**Issue by albaizq** [oeg-upm/helio#12]
Helio always redirect to port 8080: 

`2021-02-16 11:43:46.622 ERROR 1804 --- [nio-8081-exec-3] s.c.sparql.SPARQLFederatedController     : org.eclipse.rdf4j.query.QueryEvaluationException: @ sparql_localhost:8080_sparql-393cb7f5c1a61611f07a16c4e5865d51 - Request failed with status 404: http://localhost:8080/sparql-393cb7f5c1a61611f07a16c4e5865d51?query=%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E+%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E+%0A%0ASELECT+*+WHERE%7B+%0A++%3Fts+%3Fp+%3Fo+.+%0A%7D%0A.`

**Comment by AndreaCimminoArriaga** [comment]
Solved with release v0.3.8
