### ISSUE TITLE
Helio does not concatenate values from datasource

### ISSUE THREAD

**Issue by Salva5297** [oeg-upm/helio#13]
If i try this subject: "https://bimerr.iot.linkeddata.es/resource/weather/{$.measure_property}/{$.metadata_time}"

I dont get any triplet, but if i try this subject: "https://bimerr.iot.linkeddata.es/resource/weather/{$.metadata_time}"
or this subject: "https://bimerr.iot.linkeddata.es/resource/weather/{$.measure_property}"

I get all the triplets correctly.

**Comment by AndreaCimminoArriaga** [comment]
Hi, thanks for reporting. The new release of the materialiser v0.3.13 fixes this problem, and the publisher v0.3.11 integrates the fixed version of the materialiser.
