### ISSUE TITLE
Problem parsing tokens

### ISSUE THREAD

**Issue by Salva5297** [oeg-upm/Helio#3]
When I try to parse this json path: 
" _**$.Occupants.[Age]**_ "

I get this error: 
" _ERROR helio.materialiser.executors.ExecutableRule - com.jayway.jsonpath.InvalidPathException: Could not parse token starting at position 12. Expected ?, ', 0-9, *_ "

It seems that Helio don't recognize elements inside an array in json, if this element is not "_?,',0-9,*_"

**Comment by AndreaCimminoArriaga** [comment]
could you show the json file and the mappings been used?

**Comment by Salva5297** [comment]
[Example.zip](https://github.com/oeg-upm/Helio/files/5123624/Example.zip)

There is the example

**Comment by AndreaCimminoArriaga** [comment]
After some experimentation seems that the underlaying library jayway has some issues filtering the json. As a solution you can express the same filtering as  $.Occupants.[*] .Age, this will work perfectly.
