### ISSUE TITLE
I can't execute queries in Helio 

### ISSUE THREAD

**Issue by paoespinozarias** [oeg-upm/helio#4]
I executed Helio Publisher (release version 0.3.4) to publish an NT file, but when I tried to execute a query I got the following error: 
"org.apache.jena.shared. No ReaderForLangException: Reader not found NTRIPLES"

**Comment by AndreaCimminoArriaga** [comment]
We have identified the problem. Next release will fix this problem

**Comment by AndreaCimminoArriaga** [comment]
Release 0.3.7 solves the issue
