### ISSUE TITLE
Problem with subject replacements.

### ISSUE THREAD

**Issue by Salva5297** [oeg-upm/helio#8]
I have 2 resources rules that creates the same subject, Helio only stores data related to one and removes the data related to the other subject.

Example:

- **How Helio generates de data.**

@base          <http://helio.linkeddata.es/> .
<https://bimerr.iot.linkeddata.es/resource/16Y9ahzJ5DjhmNdLJbEHS9_1wyeFgulzFhhJwSLyhKQkT_Zone2>
        a       <https://bimerr.iot.linkeddata.es/def/building#Apartment> ;
        <https://bimerr.iot.linkeddata.es/def/building#hasSpace>
                <https://bimerr.iot.linkeddata.es/resource/16Y9ahzJ5DjhmNdLJbEHS9_1wyeFgulzFhhJwSLyhKQkT_31gUPiJjz4Qvpt6sZCOGVi> .

<https://bimerr.iot.linkeddata.es/resource/16Y9ahzJ5DjhmNdLJbEHS9_1wyeFgulzFhhJwSLyhKQk2_Zone1>
        a       <https://bimerr.iot.linkeddata.es/def/building#Apartment> ;
        <https://bimerr.iot.linkeddata.es/def/building#hasSpace>
                <https://bimerr.iot.linkeddata.es/resource/16Y9ahzJ5DjhmNdLJbEHS9_1wyeFgulzFhhJwSLyhKQk2_31gUPiJjz4Qvpt6sZCOGVe> .

- **How the data should be generated.**

@base          <http://helio.linkeddata.es/> .
<https://bimerr.iot.linkeddata.es/resource/16Y9ahzJ5DjhmNdLJbEHS9_1wyeFgulzFhhJwSLyhKQkT_Zone2>
        a       <https://bimerr.iot.linkeddata.es/def/building#Apartment> ;
        <https://bimerr.iot.linkeddata.es/def/building#hasSpace>
                <https://bimerr.iot.linkeddata.es/resource/16Y9ahzJ5DjhmNdLJbEHS9_1wyeFgulzFhhJwSLyhKQkT_31gUPiJjz4Qvpt6sZCOGVi> .

<https://bimerr.iot.linkeddata.es/resource/16Y9ahzJ5DjhmNdLJbEHS9_1wyeFgulzFhhJwSLyhKQk2_Zone1>
        a       <https://bimerr.iot.linkeddata.es/def/building#Apartment> ;
        <https://bimerr.iot.linkeddata.es/def/building#hasSpace>
                <https://bimerr.iot.linkeddata.es/resource/16Y9ahzJ5DjhmNdLJbEHS9_1wyeFgulzFhhJwSLyhKQk2_31gUPiJjz4Qvpt6sZCOGVg> , <https://bimerr.iot.linkeddata.es/resource/16Y9ahzJ5DjhmNdLJbEHS9_1wyeFgulzFhhJwSLyhKQk2_31gUPiJjz4Qvpt6sZCOGVk> , <https://bimerr.iot.linkeddata.es/resource/16Y9ahzJ5DjhmNdLJbEHS9_1wyeFgulzFhhJwSLyhKQk2_31gUPiJjz4Qvpt6sZCOGVe> .

**Comment by AndreaCimminoArriaga** [comment]
This problem was notified also by other users, the new release (0.3.7) will solve this issue
