### ISSUE TITLE
Helio-storage contains data from different Helio executions

### ISSUE THREAD

**Issue by Salva5297** [oeg-upm/helio#9]
The flow to reproduce this issue is the following one:

1. I run Helio with a mapping M_1
2. Then I run Helio with a mapping M_2 that is different from M_1
3. The RDF produced with M_2 also contains the RDF of M_1.

I think helio-storage does not remove the RDF of M_1 when I run the mapping M_2.

**Comment by AndreaCimminoArriaga** [comment]
This is true, the idea is that the helio-storage contains a copy of the generated RDF. When the mappings are changed the helio-storage should be removed and created again. To simplify this behaviour the new release (0.3.7) will have a special command that is **--clear** to indicate to Helio that the helio-storage has to be created from scratch.

**Comment by AndreaCimminoArriaga** [comment]
New release ready & issue solved
